#! /bin/sh

# test ETH -> curl 127.0.0.8/content/bitsofcode.eth
# dig @127.0.0.8 bitsofcode.eth uri


docker run -it \
	-m 1g \
	--read-only \
	-v ${PWD}/data:/opt/data/ \
	--env SYSLOG_STDOUT=Y \
	--env "ALCHEMY_API_CODE=${ALCHEMY_API_CODE}" \
	--env "UWR_IP_ADDRESSES=78.129.239.31" \
	-p 127.0.0.8:53:53/udp \
	-p 127.0.0.8:80:8081 \
	ethereum-dns-gateway $*
